disabled_rules:
  - force_cast
  - leading_whitespace
  - trailing_whitespace

opt_in_rules:
  - closure_spacing

line_length:
  warning: 120
  error: 150

type_name:
  min_length:
    warning: 3
    error: 4
  max_length:
    warning: 40
    error: 50

